### ISSUE TITLE
Cmpiling issue in Mac OSX

### ISSUE THREAD

**Issue by DromaninCM** [mesonepigreco/CellConstructor#33]
Hi,

I have changed laptop and consequently the operating system: now it is Mac OS X Big Sur.
I just wanted to signal that I installed again cellconsructor after cloning it from GitHub and there was an issue during the installation: 

clang: CModules/LinAlg.c
CModules/LinAlg.c:28:16: error: implicitly declaring library function 'calloc' with type 'void *(unsigned long, unsigned long)' [-Werror,-Wimplicit-function-declaration]
  f_n=(double*)calloc(L, sizeof(double)); 
               ^
CModules/LinAlg.c:28:16: note: include the header <stdlib.h> or explicitly provide a declaration for 'calloc'

I solved by adding in CModules/LinAlg.c:
#include <stdlib.h>

Best,

Davide

**Comment by mesonepigreco** [comment]
Thanks for spotting this issue, 
fixed in commit 992a705092a49e3d8fa4d8752633c2c9dc2dfa22
The new version of the master should work now :)
